version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"
    env_file:
      - .env
    

  frontend:
    build:
      context: ./fridgeui
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
      dockerfile: Dockerfile.react 
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "3000:80"
    depends_on:
      - backend
