version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

      # - .env
    

  frontend:
    build:
      context: ./fridgeui
      dockerfile: Dockerfile.react
      args:
# <<<<<<< HEAD
        REACT_APP_API_URL: "${REACT_APP_API_URL:-http://3.139.71.177:8000/}"
      dockerfile: Dockerfile.react 
# =======
#         # - REACT_APP_API_URL=${REACT_APP_API_URL}
#       dockerfile: Dockerfile.react 
# >>>>>>> main
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://3.139.71.177:8000/}
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
