version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.django
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./fridgeui
      dockerfile: Dockerfile.react 
    ports:
      - "3000:80"
    depends_on:
      - backend
