# Generated by Django 5.1.6 on 2025-02-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=36, unique=True),
        ),
    ]
