# Generated by Django 5.1.6 on 2025-02-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_food_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='food',
            name='Expire_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='Production_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
