# Generated by Django 5.1.6 on 2025-02-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_recipe_user_fridgeitem_userrecipelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeitem',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userrecipelog',
            name='recipe_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userrecipelog',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
