# Generated by Django 5.1.6 on 2025-02-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_fridgeitem_uid_alter_userrecipelog_recipe_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
