# Generated by Django 5.1.6 on 2025-03-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilepic',
            new_name='profile_pic',
        ),
    ]
