# Generated by Django 5.1.6 on 2025-03-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='allergics',
            new_name='allergies',
        ),
        migrations.AddField(
            model_name='recipe',
            name='direction',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
