# Generated by Django 5.1.6 on 2025-03-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
