# Generated by Django 5.1.6 on 2025-03-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
