# Generated by Django 5.1.6 on 2025-03-02 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipelog',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recipe'),
        ),
        migrations.AlterField(
            model_name='userrecipelog',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
