# Generated by Django 5.1.6 on 2025-03-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userrecipelog_recipe_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecipelog',
            unique_together={('userid', 'recipe_id', 'op')},
        ),
    ]
