# Generated by Django 5.1.6 on 2025-03-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemtag'),
        ('core', '0008_alter_userrecipelog_unique_together'),
    ]

    operations = [
    ]
