name: Auto Deploy to EC2 (push Docker image)

on:
  push:
    branches:
      - deploy  # 或你要监听的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build backend image
      run: |
        docker buildx build --platform linux/amd64 -t fridge-backend -f backend/Dockerfile.django --output type=docker backend
        docker save fridge-backend -o fridge-backend.tar

    - name: Build frontend image
      run: |
        docker buildx build --platform linux/amd64 -t fridge-frontend -f fridgeui/Dockerfile.react --output type=docker fridgeui
        docker save fridge-frontend -o fridge-frontend.tar

    - name: Copy images to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "fridge-backend.tar,fridge-frontend.tar"
        target: "~/"

    - name: SSH and deploy on EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load -i fridge-backend.tar
          docker load -i fridge-frontend.tar

          docker stop backend || true && docker rm backend || true
          docker stop frontend || true && docker rm frontend || true

          docker run -d --name backend -p 8000:8000 fridge-backend
          docker run -d --name frontend -p 80:80 fridge-frontend
