name: Django CI

on:
  push:
    branches: ['showcase-lily']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # 3. Install system dependencies for mysqlclient (if using MySQL in backend)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev build-essential

      # 4. Install backend dependencies (requirements.txt is located in the backend folder)
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # 5. Install mysqlclient module (if not included in requirements.txt)
      - name: Install mysqlclient module
        run: pip install mysqlclient

      # 6. Install coverage (for backend test coverage reporting)
      - name: Install coverage
        run: pip install coverage

      # 7. Run database migrations
      - name: Migrate & run backend tests
        env:
          DJANGO_ENV: test
        run: |
          cd backend
          python manage.py makemigrations --noinput
          python manage.py migrate --noinput
          coverage run --source=core manage.py test core.test_core
          coverage report -m

      # 8. Run backend tests with coverage reporting
      - name: Start backend server
        env:
              DJANGO_ENV: test 
        run: |
          cd backend
          nohup python manage.py runserver 0.0.0.0:8000 &


          sleep 10
          

      # 9. Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd fridgeui
          npm install

      - name: Check if SQLite DB file exists
        run: |
          ls -al backend/db.sqlite3 || echo "DB does not exist"


      # 10. start frontend service
      - name: Start frontend server
        run: |
          cd fridgeui
          nohup npm start &

          sleep 20

      # 11. install Chromium & Chromedriver
      - name: Install Chrome and Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV


      # 12. run Selenium test
      - name: Run Selenium tests 
        env:
          GITHUB_ACTIONS: true
        run: |
          pip install selenium pytest webdriver-manager
          pytest tests/test_selenium.py --maxfail=1 --disable-warnings -q

      - name: Tail Django log for debug
        run: tail -n 100 nohup.out || echo "No logs yet"
