name: Django CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # 3. Install system dependencies for mysqlclient and build tools
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev build-essential

      # 4. Install backend dependencies
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # 5. Install mysqlclient module (if not already in requirements.txt)
      - name: Install mysqlclient module
        run: pip install mysqlclient

      # 6. Install coverage for backend test reporting
      - name: Install coverage
        run: pip install coverage

      # 7. Run database migrations
      - name: Run migrations
        run: |
          python backend/manage.py makemigrations --noinput
          python backend/manage.py migrate --noinput

      # 8. Run backend tests with coverage reporting
      - name: Run backend tests with coverage
        run: |
          coverage run --source=. backend/manage.py core test
          coverage report -m

      # # 9. Install frontend dependencies and run frontend tests
      # - name: Run frontend tests
      #   run: |
      #     cd fridgeui
      #     npm install
      #     npm test -- --coverage
