name: Django CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # 3. Install system dependencies for mysqlclient (if using MySQL in backend)
      - name: Install system dependencies for mysqlclient
        run: |
          sudo apt-get update
          sudo apt-get install -y default-libmysqlclient-dev build-essential

      # 4. Install backend dependencies (requirements.txt is located in the backend folder)
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # 5. Install mysqlclient module (if not included in requirements.txt)
      - name: Install mysqlclient module
        run: pip install mysqlclient

      # 6. Install coverage (for backend test coverage reporting)
      - name: Install coverage
        run: pip install coverage

      # 7. Run database migrations
      - name: Run migrations
        run: |
          python backend/manage.py makemigrations --noinput
          python backend/manage.py migrate --noinput

      # 8. Run backend tests with coverage reporting
      - name: Run backend tests with coverage
        run: |
          coverage run --source=core backend/manage.py test core.test_core
          coverage report -m

      # # 9. Install frontend dependencies and run frontend tests
      # - name: Run frontend tests
      #   run: |
      #     cd fridgeui
      #     npm install
      #     npm test -- --coverage

      # 10. 运行 Selenium 测试
      - name: Run Selenium tests
        run: |
          pip install selenium pytest
          pytest tests/test_selenium.py --maxfail=1 --disable-warnings -q
